[package]
name = "kvstore-rs"
version = "0.1.0"
edition = "2021"
description = "A simple key-value store"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
